package com.agentplatform.knowledge;

import org.apache.pdfbox.Loader;import org.apache.pdfbox.text.PDFTextStripper;import org.apache.poi.xwpf.usermodel.XWPFDocument;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Service;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Instant;import java.util.UUID;

@Service public class DocumentProcessor {
 private final JdbcTemplate jdbc;private final StorageProperties storage;
 public DocumentProcessor(JdbcTemplate jdbc,StorageProperties storage){this.jdbc=jdbc;this.storage=storage;}
 @Async public void process(UUID jobId,UUID versionId,String storageKey,String mediaType){jdbc.update("UPDATE document_job SET status='RUNNING',attempt=attempt+1,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),jobId.toString());jdbc.update("UPDATE document_version SET parse_status='PARSING',failure_code=NULL WHERE id=?",versionId.toString());try{Path p=Path.of(storage.root()).resolve(storageKey).normalize();String text;int pages=0;if(mediaType.equals("application/pdf")){try(var doc=Loader.loadPDF(p.toFile())){pages=doc.getNumberOfPages();text=new PDFTextStripper().getText(doc);}}else if(mediaType.equals("application/vnd.openxmlformats-officedocument.wordprocessingml.document")){try(var in=Files.newInputStream(p);var doc=new XWPFDocument(in)){text=doc.getParagraphs().stream().map(x->x.getText()).reduce("",(a,b)->a+b+"\n");}}else{text=Files.readString(p,StandardCharsets.UTF_8);}if(text.isBlank())throw new IOException("EMPTY_TEXT");jdbc.update("UPDATE document_version SET parse_status='PARSED',extracted_text=?,page_count=? WHERE id=?",text,pages==0?null:pages,versionId.toString());jdbc.update("UPDATE document_job SET status='COMPLETED',error_code=NULL,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),jobId.toString());}catch(Exception e){jdbc.update("UPDATE document_version SET parse_status='FAILED',failure_code='PARSE_FAILED' WHERE id=?",versionId.toString());jdbc.update("UPDATE document_job SET status='FAILED',error_code='PARSE_FAILED',updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),jobId.toString());}}
}
