package com.agentplatform.knowledge;

import com.agentplatform.common.BusinessException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class KnowledgeIndexService {
 private final JdbcTemplate jdbc;private final EmbeddingClient embeddings;private final ObjectMapper json;
 public KnowledgeIndexService(JdbcTemplate jdbc,EmbeddingClient embeddings,ObjectMapper json){this.jdbc=jdbc;this.embeddings=embeddings;this.json=json;}
 @Async("documentTaskExecutor") public void build(UUID generationId){try{jdbc.update("UPDATE kb_generation SET status='RUNNING',failure_code=NULL WHERE id=?",generationId.toString());ensurePgVector();Map<String,Object> generation=jdbc.queryForMap("SELECT kb_id,embedding_id FROM kb_generation WHERE id=?",generationId.toString());UUID embeddingId=UUID.fromString(String.valueOf(generation.get("embedding_id")));List<Map<String,Object>> docs=jdbc.queryForList("SELECT v.id version_id,v.extracted_text,v.page_count,d.normalized_name FROM document d JOIN document_version v ON v.document_id=d.id WHERE d.kb_id=? AND d.removed_at IS NULL AND v.parse_status='PARSED' AND v.version_no=(SELECT MAX(v2.version_no) FROM document_version v2 WHERE v2.document_id=d.id) ORDER BY d.normalized_name",String.valueOf(generation.get("kb_id")));List<Chunk> chunks=new ArrayList<>();for(Map<String,Object> doc:docs)chunks.addAll(chunk(String.valueOf(doc.get("version_id")),String.valueOf(doc.get("extracted_text")),doc.get("page_count")==null?null:((Number)doc.get("page_count")).intValue()));if(chunks.isEmpty())throw new BusinessException(422,"NO_DOCUMENT_CONTENT","没有可索引的文档内容");jdbc.update("DELETE FROM document_chunk WHERE generation_id=?",generationId.toString());for(int start=0;start<chunks.size();start+=16){List<Chunk> batch=chunks.subList(start,Math.min(start+16,chunks.size()));List<float[]> vectors=embeddings.embed(embeddingId,batch.stream().map(Chunk::content).toList());for(int i=0;i<batch.size();i++){Chunk chunk=batch.get(i);float[] vector=vectors.get(i);jdbc.update("INSERT INTO document_chunk(id,generation_id,document_version_id,chunk_index,page_number,content,token_count,embedding_json,embedding_vector,created_at) VALUES(?,?,?,?,?,?,?,?,CAST(? AS vector),?)",UUID.randomUUID().toString(),generationId.toString(),chunk.versionId,chunk.index,chunk.page,chunk.content,Math.max(1,chunk.content.length()/2),json.writeValueAsString(vector),EmbeddingClient.vector(vector),com.agentplatform.common.DatabaseTime.now());}}
  var now=com.agentplatform.common.DatabaseTime.now();jdbc.update("UPDATE kb_generation SET status='SUPERSEDED' WHERE kb_id=? AND status='PUBLISHED'",String.valueOf(generation.get("kb_id")));jdbc.update("UPDATE kb_generation SET status='PUBLISHED',chunk_count=?,document_count=?,published_at=?,failure_code=NULL WHERE id=?",chunks.size(),docs.size(),now,generationId.toString());jdbc.update("UPDATE knowledge_base SET active_generation_id=?,revision=revision+1,updated_at=? WHERE id=?",generationId.toString(),now,String.valueOf(generation.get("kb_id")));
 }catch(Exception e){jdbc.update("UPDATE kb_generation SET status='FAILED',failure_code=? WHERE id=?",failure(e),generationId.toString());}}
 private void ensurePgVector(){try(var connection=Objects.requireNonNull(jdbc.getDataSource()).getConnection()){String product=connection.getMetaData().getDatabaseProductName();if(!product.toLowerCase(Locale.ROOT).contains("postgresql"))throw new BusinessException(422,"PGVECTOR_REQUIRED","知识库索引需要 PostgreSQL + pgvector");jdbc.execute("CREATE EXTENSION IF NOT EXISTS vector");jdbc.execute("ALTER TABLE document_chunk ADD COLUMN IF NOT EXISTS embedding_vector vector NOT NULL");}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(422,"PGVECTOR_UNAVAILABLE","无法初始化 pgvector，请确认扩展已安装且数据库账号具有使用权限");}}
 private List<Chunk> chunk(String versionId,String text,Integer pages){List<Chunk> result=new ArrayList<>();String normalized=text.replace("\u0000","").replaceAll("[ \\t]+"," ").trim();int index=0;for(int start=0;start<normalized.length();){int end=Math.min(start+1200,normalized.length());if(end<normalized.length()){int boundary=Math.max(normalized.lastIndexOf('\n',end),normalized.lastIndexOf('。',end));if(boundary>start+600)end=boundary+1;}String content=normalized.substring(start,end).trim();if(!content.isBlank()){Integer page=pages==null?null:Math.min(pages,1+(int)((long)start*pages/Math.max(1,normalized.length())));result.add(new Chunk(versionId,index++,page,content));}if(end>=normalized.length())break;start=Math.max(start+1,end-200);}return result;}
 private String failure(Exception e){if(e instanceof BusinessException b)return b.code();return "INDEX_BUILD_FAILED";}
 private record Chunk(String versionId,int index,Integer page,String content){}
}
