package com.agentplatform.knowledge;
import com.agentplatform.common.BusinessException;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api/v1/admin/knowledge-bases") public class KnowledgeGenerationController{
 private final JdbcTemplate jdbc;private final KnowledgeIndexService indexer;public KnowledgeGenerationController(JdbcTemplate jdbc,KnowledgeIndexService indexer){this.jdbc=jdbc;this.indexer=indexer;}
 @GetMapping("/{id}/generations") public List<Map<String,Object>> list(@PathVariable UUID id){return jdbc.queryForList("SELECT id,generation_no,status,document_count,chunk_count,failure_code,created_at,published_at FROM kb_generation WHERE kb_id=? ORDER BY generation_no DESC",id.toString());}
 @PostMapping("/{id}/reindex") @ResponseStatus(HttpStatus.ACCEPTED) public Map<String,Object> reindex(@PathVariable UUID id){Map<String,Object> kb=jdbc.queryForMap("SELECT embedding_id FROM knowledge_base WHERE id=?",id.toString());if(kb.get("embedding_id")==null)throw new BusinessException(422,"EMBEDDING_REQUIRED","请先配置 Embedding 模型");Integer parsed=jdbc.queryForObject("SELECT COUNT(*) FROM document d JOIN document_version v ON v.document_id=d.id WHERE d.kb_id=? AND d.removed_at IS NULL AND v.parse_status='PARSED' AND v.version_no=(SELECT MAX(v2.version_no) FROM document_version v2 WHERE v2.document_id=d.id)",Integer.class,id.toString());if(parsed==null||parsed==0)throw new BusinessException(422,"NO_PARSED_DOCUMENTS","没有可用于建索引的已解析文档");Integer no=jdbc.queryForObject("SELECT COALESCE(MAX(generation_no),0)+1 FROM kb_generation WHERE kb_id=?",Integer.class,id.toString());UUID generation=UUID.randomUUID();jdbc.update("INSERT INTO kb_generation(id,kb_id,embedding_id,generation_no,status,document_count,failure_code,created_at) VALUES(?,?,?,?,'QUEUED',?,NULL,?)",generation.toString(),id.toString(),String.valueOf(kb.get("embedding_id")),no,parsed,com.agentplatform.common.DatabaseTime.now());indexer.build(generation);return Map.of("generationId",generation,"status","QUEUED");}
 @PostMapping("/{id}/enable") public void enable(@PathVariable UUID id){int n=jdbc.update("UPDATE knowledge_base SET enabled=TRUE,revision=revision+1,updated_at=? WHERE id=? AND active_generation_id IS NOT NULL",com.agentplatform.common.DatabaseTime.now(),id.toString());if(n==0)throw new BusinessException(422,"KNOWLEDGE_NOT_INDEXED","存在已发布索引后才能启用知识库");}
 @PostMapping("/{id}/disable") public void disable(@PathVariable UUID id){jdbc.update("UPDATE knowledge_base SET enabled=FALSE,revision=revision+1,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),id.toString());}
}
