package com.agentplatform.config;

import com.agentplatform.common.BusinessException;
import com.agentplatform.identity.PlatformPrincipal;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api/v1/admin")
public class ConfigurationCatalogController {
 private final JdbcTemplate jdbc; private final SecretService secrets;
 public ConfigurationCatalogController(JdbcTemplate jdbc,SecretService secrets){this.jdbc=jdbc;this.secrets=secrets;}

 @GetMapping("/models") public List<Map<String,Object>> models(){return listConfigs("model_config","model_version","model_id");}
 @PostMapping("/models") @Transactional public Map<String,Object> createModel(@Valid @RequestBody ModelRequest r,Authentication a){return createConfig("model",r.displayName(),r.provider(),r.endpoint(),r.modelName(),r.apiKey(),r.timeoutMs(),actor(a));}
 @PutMapping("/models/{id}") @Transactional public Map<String,Object> updateModel(@PathVariable UUID id,@Valid @RequestBody ModelRequest r,Authentication a){return updateConfig("model",id,r,actor(a));}
 @DeleteMapping("/models/{id}") @Transactional public void deleteModel(@PathVariable UUID id){deleteConfig("model",id);}
 @PostMapping("/models/{id}/enable") @Transactional public void enableModel(@PathVariable UUID id){enable("model",id);}
 @PostMapping("/models/{id}/disable") public void disableModel(@PathVariable UUID id){jdbc.update("UPDATE model_config SET enabled=FALSE,revision=revision+1,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),id.toString());}

 @GetMapping("/embedding-models") public List<Map<String,Object>> embeddings(){return listConfigs("embedding_config","embedding_version","embedding_id");}
 @PostMapping("/embedding-models") @Transactional public Map<String,Object> createEmbedding(@Valid @RequestBody ModelRequest r,Authentication a){return createConfig("embedding",r.displayName(),r.provider(),r.endpoint(),r.modelName(),r.apiKey(),r.timeoutMs(),actor(a));}
 @PutMapping("/embedding-models/{id}") @Transactional public Map<String,Object> updateEmbedding(@PathVariable UUID id,@Valid @RequestBody ModelRequest r,Authentication a){return updateConfig("embedding",id,r,actor(a));}
 @DeleteMapping("/embedding-models/{id}") @Transactional public void deleteEmbedding(@PathVariable UUID id){deleteConfig("embedding",id);}
 @PostMapping("/embedding-models/{id}/enable") @Transactional public void enableEmbedding(@PathVariable UUID id){enable("embedding",id);}
 @PostMapping("/embedding-models/{id}/disable") public void disableEmbedding(@PathVariable UUID id){jdbc.update("UPDATE embedding_config SET enabled=FALSE,revision=revision+1,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),id.toString());}

 @GetMapping("/data-sources") public List<Map<String,Object>> sources(){return jdbc.queryForList("""
  SELECT c.id,c.name,c.type,c.enabled,c.revision,v.endpoint,v.database_name,v.index_name,v.username,v.timezone,v.purpose,
  v.test_status,v.read_only_verified,(v.secret_version_id IS NOT NULL) has_secret
  FROM data_source c JOIN data_source_version v ON v.id=c.active_version_id ORDER BY c.created_at DESC
  """);}
 @PostMapping("/data-sources") @Transactional public Map<String,Object> createSource(@Valid @RequestBody DataSourceRequest r,Authentication a){
  if(!Set.of("MYSQL","ELASTICSEARCH").contains(r.type()))throw new BusinessException(422,"SOURCE_TYPE_INVALID","仅支持 MySQL 或 Elasticsearch");
  UUID id=UUID.randomUUID(),vid=UUID.randomUUID();java.sql.Timestamp now=com.agentplatform.common.DatabaseTime.now();UUID sid=secrets.store(r.password(),"DATA_SOURCE",actor(a));
  try{jdbc.update("INSERT INTO data_source(id,name,type,enabled,active_version_id,revision,created_at,updated_at) VALUES(?,?,?,FALSE,NULL,1,?,?)",id.toString(),r.name().trim(),r.type(),now,now);
   jdbc.update("INSERT INTO data_source_version(id,source_id,version_no,endpoint,database_name,index_name,username,secret_version_id,timezone,purpose,test_status,read_only_verified,created_by,created_at) VALUES(?,?,1,?,?,?,?,?, ?,?,'UNTESTED',FALSE,?,?)",vid.toString(),id.toString(),r.endpoint(),blank(r.databaseName()),blank(r.indexName()),blank(r.username()),sid==null?null:sid.toString(),r.timezone(),r.purpose(),actor(a).id().toString(),now);
   jdbc.update("UPDATE data_source SET active_version_id=? WHERE id=?",vid.toString(),id.toString());return Map.of("id",id.toString());
  }catch(Exception e){throw duplicate(e,"数据源名称已存在");}
 }
 @PostMapping("/data-sources/{id}/publish") @Transactional public void publishSource(@PathVariable UUID id,Authentication a){int n=jdbc.update("UPDATE data_source SET enabled=TRUE,revision=revision+1,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM data_source_version v WHERE v.id=data_source.active_version_id AND v.test_status='PASSED' AND v.schema_json IS NOT NULL AND v.allowed_objects_json IS NOT NULL)",com.agentplatform.common.DatabaseTime.now(),id.toString());if(n==0)throw new BusinessException(422,"SOURCE_NOT_READY","连接、结构和授权范围全部通过后才能发布");String version=jdbc.queryForObject("SELECT active_version_id FROM data_source WHERE id=?",String.class,id.toString());jdbc.update("INSERT INTO publication_record(id,config_type,config_id,version_id,data_sending_confirmed,confirmed_by,published_at) VALUES(?,?,?,?,TRUE,?,?)",UUID.randomUUID().toString(),"DATA_SOURCE",id.toString(),version,actor(a).id().toString(),com.agentplatform.common.DatabaseTime.now());}
 @PostMapping("/data-sources/{id}/disable") public void disableSource(@PathVariable UUID id){jdbc.update("UPDATE data_source SET enabled=FALSE,revision=revision+1,updated_at=? WHERE id=?",com.agentplatform.common.DatabaseTime.now(),id.toString());}

 @GetMapping("/knowledge-bases") public List<Map<String,Object>> knowledge(){return jdbc.queryForList("SELECT k.id,k.name,k.description,k.enabled,k.revision,k.embedding_id,e.display_name embedding_name FROM knowledge_base k LEFT JOIN embedding_config e ON e.id=k.embedding_id ORDER BY k.created_at DESC");}
 @PostMapping("/knowledge-bases") public Map<String,Object> createKnowledge(@Valid @RequestBody KnowledgeRequest r){UUID id=UUID.randomUUID();java.sql.Timestamp now=com.agentplatform.common.DatabaseTime.now();if(r.embeddingId()!=null){Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM embedding_config WHERE id=? AND enabled=TRUE",Integer.class,r.embeddingId().toString());if(count==null||count==0)throw new BusinessException(422,"EMBEDDING_NOT_ENABLED","请选择已启用的 Embedding 模型");}try{jdbc.update("INSERT INTO knowledge_base(id,name,description,embedding_id,enabled,revision,created_at,updated_at) VALUES(?,?,?,?,FALSE,1,?,?)",id.toString(),r.name().trim(),r.description().trim(),r.embeddingId()==null?null:r.embeddingId().toString(),now,now);return Map.of("id",id.toString());}catch(Exception e){throw duplicate(e,"知识库名称已存在");}}

 private Map<String,Object> createConfig(String kind,String name,String provider,String endpoint,String modelName,String apiKey,int timeout,PlatformPrincipal actor){if(!Set.of("OPENAI","OLLAMA").contains(provider))throw new BusinessException(422,"PROVIDER_INVALID","供应商仅支持 OPENAI 或 OLLAMA");String ct=kind.equals("model")?"model_config":"embedding_config",vt=kind.equals("model")?"model_version":"embedding_version",fk=kind.equals("model")?"model_id":"embedding_id";UUID id=UUID.randomUUID(),vid=UUID.randomUUID(),sid=secrets.store(apiKey,kind.toUpperCase(Locale.ROOT),actor);java.sql.Timestamp now=com.agentplatform.common.DatabaseTime.now();try{jdbc.update("INSERT INTO "+ct+"(id,display_name,enabled,active_version_id,revision,created_at,updated_at) VALUES(?,?,FALSE,NULL,1,?,?)",id.toString(),name.trim(),now,now);jdbc.update("INSERT INTO "+vt+"(id,"+fk+",version_no,provider,endpoint,model_name,secret_version_id,timeout_ms,test_status,created_by,created_at) VALUES(?,?,1,?,?,?,?,?,'UNTESTED',?,?)",vid.toString(),id.toString(),provider,endpoint,modelName,sid==null?null:sid.toString(),timeout,actor.id().toString(),now);jdbc.update("UPDATE "+ct+" SET active_version_id=? WHERE id=?",vid.toString(),id.toString());return Map.of("id",id.toString());}catch(Exception e){throw duplicate(e,"配置名称已存在");}}
 private Map<String,Object> updateConfig(String kind,UUID id,ModelRequest r,PlatformPrincipal actor){if(!Set.of("OPENAI","OLLAMA").contains(r.provider()))throw new BusinessException(422,"PROVIDER_INVALID","供应商仅支持 OPENAI 或 OLLAMA");String ct=kind.equals("model")?"model_config":"embedding_config",vt=kind.equals("model")?"model_version":"embedding_version",fk=kind.equals("model")?"model_id":"embedding_id";List<Map<String,Object>> current=jdbc.queryForList("SELECT c.revision,v.version_no,v.secret_version_id FROM "+ct+" c JOIN "+vt+" v ON v.id=c.active_version_id WHERE c.id=?",id.toString());if(current.isEmpty())throw new BusinessException(404,"CONFIG_NOT_FOUND","模型配置不存在");Map<String,Object> old=current.getFirst();UUID sid=r.apiKey()==null||r.apiKey().isBlank()?(old.get("secret_version_id")==null?null:UUID.fromString(String.valueOf(old.get("secret_version_id")))):secrets.store(r.apiKey(),kind.toUpperCase(Locale.ROOT),actor);int next=((Number)old.get("version_no")).intValue()+1;long revision=((Number)old.get("revision")).longValue()+1;UUID vid=UUID.randomUUID();var now=com.agentplatform.common.DatabaseTime.now();try{jdbc.update("INSERT INTO "+vt+"(id,"+fk+",version_no,provider,endpoint,model_name,secret_version_id,timeout_ms,test_status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,'UNTESTED',?,?)",vid.toString(),id.toString(),next,r.provider(),r.endpoint().trim(),r.modelName().trim(),sid==null?null:sid.toString(),r.timeoutMs(),actor.id().toString(),now);jdbc.update("UPDATE "+ct+" SET display_name=?,enabled=FALSE,active_version_id=?,revision=?,updated_at=? WHERE id=?",r.displayName().trim(),vid.toString(),revision,now,id.toString());return Map.of("id",id.toString(),"revision",revision);}catch(Exception e){throw duplicate(e,"配置名称已存在");}}
 private void deleteConfig(String kind,UUID id){String ct=kind.equals("model")?"model_config":"embedding_config",vt=kind.equals("model")?"model_version":"embedding_version",fk=kind.equals("model")?"model_id":"embedding_id";Integer exists=jdbc.queryForObject("SELECT COUNT(*) FROM "+ct+" WHERE id=?",Integer.class,id.toString());if(exists==null||exists==0)throw new BusinessException(404,"CONFIG_NOT_FOUND","模型配置不存在");String referenceSql=kind.equals("model")?"SELECT COUNT(*) FROM chat_conversation WHERE model_id=?":"SELECT (SELECT COUNT(*) FROM knowledge_base WHERE embedding_id=?)+(SELECT COUNT(*) FROM kb_generation WHERE embedding_id=?)";Integer references=kind.equals("model")?jdbc.queryForObject(referenceSql,Integer.class,id.toString()):jdbc.queryForObject(referenceSql,Integer.class,id.toString(),id.toString());if(references!=null&&references>0)throw new BusinessException(409,"CONFIG_IN_USE","该模型已被会话或知识库使用，只能停用，不能删除");List<String> secretIds=jdbc.queryForList("SELECT secret_version_id FROM "+vt+" WHERE "+fk+"=? AND secret_version_id IS NOT NULL",String.class,id.toString());jdbc.update("UPDATE "+ct+" SET active_version_id=NULL WHERE id=?",id.toString());jdbc.update("DELETE FROM "+vt+" WHERE "+fk+"=?",id.toString());jdbc.update("DELETE FROM "+ct+" WHERE id=?",id.toString());for(String secretId:secretIds)jdbc.update("DELETE FROM secret_version WHERE id=?",secretId);}
 private List<Map<String,Object>> listConfigs(String ct,String vt,String fk){return jdbc.queryForList("SELECT c.id,c.display_name,c.enabled,c.revision,v.provider,v.endpoint,v.model_name,v.timeout_ms,v.test_status,(v.secret_version_id IS NOT NULL) has_secret FROM "+ct+" c JOIN "+vt+" v ON v.id=c.active_version_id ORDER BY c.created_at DESC");}
 private void enable(String kind,UUID id){String ct=kind.equals("model")?"model_config":"embedding_config",vt=kind.equals("model")?"model_version":"embedding_version";int n=jdbc.update("UPDATE "+ct+" SET enabled=TRUE,revision=revision+1,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM "+vt+" v WHERE v.id="+ct+".active_version_id AND v.test_status='PASSED')",com.agentplatform.common.DatabaseTime.now(),id.toString());if(n==0)throw new BusinessException(422,"CONFIG_NOT_TESTED","测试通过后才能启用");}
 private static PlatformPrincipal actor(Authentication a){return (PlatformPrincipal)a.getPrincipal();} private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
 private static BusinessException duplicate(Exception e,String message){return new BusinessException(409,"NAME_EXISTS",message);}
 public record ModelRequest(@NotBlank String displayName,@NotBlank String provider,@NotBlank @Size(max=500) String endpoint,@NotBlank String modelName,String apiKey,@Min(1000) @Max(120000) int timeoutMs){}
 public record DataSourceRequest(@NotBlank String name,@NotBlank String type,@NotBlank @Size(max=500) String endpoint,String databaseName,String indexName,String username,String password,@NotBlank String timezone,@NotBlank @Size(max=1000) String purpose){}
 public record KnowledgeRequest(@NotBlank String name,@NotBlank @Size(max=1000) String description,UUID embeddingId){}
}
