package com.agentplatform.config;

import com.agentplatform.common.BusinessException;
import com.agentplatform.identity.PlatformPrincipal;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.*;import java.util.*;

@RestController @RequestMapping("/api/v1/admin/data-sources")
public class DataSourceMetadataController {
 private final JdbcTemplate jdbc;private final SecretService secrets;private final NetworkPolicyProperties network;private final ObjectMapper json;private final HttpClient http=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).build();
 public DataSourceMetadataController(JdbcTemplate jdbc,SecretService secrets,NetworkPolicyProperties network,ObjectMapper json){this.jdbc=jdbc;this.secrets=secrets;this.network=network;this.json=json;}
 @PostMapping("/{id}/schema-refresh") public Map<String,Object> refresh(@PathVariable UUID id){Config c=config(id);try{Map<String,Object> schema="MYSQL".equals(c.type)?mysql(c):es(c);String text=json.writeValueAsString(schema),hash=hex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));jdbc.update("UPDATE data_source_version SET schema_json=?,schema_hash=? WHERE id=?",text,hash,c.versionId);return Map.of("schema",schema,"schemaHash",hash);}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(502,"SCHEMA_REFRESH_FAILED","结构刷新失败："+safe(e));}}
 @GetMapping("/{id}/schema") public Map<String,Object> schema(@PathVariable UUID id){Config c=config(id);if(c.schemaJson==null)throw new BusinessException(404,"SCHEMA_NOT_REFRESHED","请先刷新结构");try{return Map.of("schema",json.readTree(c.schemaJson),"allowedObjects",c.allowedJson==null?json.createObjectNode():json.readTree(c.allowedJson),"schemaHash",c.schemaHash);}catch(Exception e){throw new BusinessException(500,"SCHEMA_INVALID","已保存结构无法读取");}}
 @PutMapping("/{id}/semantics") @Transactional public void semantics(@PathVariable UUID id,@RequestBody Semantics body,Authentication auth){Config c=config(id);if(c.schemaJson==null)throw new BusinessException(422,"SCHEMA_NOT_REFRESHED","请先刷新结构");try{if("ELASTICSEARCH".equals(c.type))validateEsSemantics(c.schemaJson,body.allowedObjects);jdbc.update("UPDATE data_source_version SET allowed_objects_json=? WHERE id=?",json.writeValueAsString(body.allowedObjects),c.versionId);jdbc.update("DELETE FROM business_metric WHERE source_version_id=?",c.versionId);if(body.metrics!=null)for(Metric m:body.metrics){if(m.name==null||m.name.isBlank()||m.expression==null)throw new BusinessException(422,"METRIC_INVALID","指标名称和表达式不能为空");jdbc.update("INSERT INTO business_metric(id,source_version_id,name,description,expression_json,time_field,filters_json,unit,rounding_rule,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c.versionId,m.name,m.description==null?"":m.description,json.writeValueAsString(m.expression),m.timeField,m.filters==null?null:json.writeValueAsString(m.filters),m.unit,m.roundingRule,com.agentplatform.common.DatabaseTime.now());}}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(422,"SEMANTICS_INVALID","业务语义保存失败");}}
 @PostMapping("/{id}/field-samples") public Map<String,List<String>> fieldSamples(@PathVariable UUID id,@RequestBody SampleRequest request){Config c=config(id);if(!"ELASTICSEARCH".equals(c.type))throw new BusinessException(422,"SOURCE_TYPE_INVALID","仅 Elasticsearch 支持字段样本");try{Set<String> schemaFields=new LinkedHashSet<>();for(JsonNode f:json.readTree(c.schemaJson).path("fields"))schemaFields.add(f.path("name").asText());List<String> fields=request.fields==null?List.of():request.fields.stream().filter(schemaFields::contains).limit(50).toList();if(fields.isEmpty())throw new BusinessException(422,"FIELD_SCOPE_EMPTY","请先选择需要采样的字段");ObjectNode body=json.createObjectNode().put("size",5);ArrayNode source=body.putArray("_source");fields.forEach(source::add);URI uri=URI.create(c.endpoint);allowed(uri.getHost());HttpRequest.Builder b=HttpRequest.newBuilder(join(uri,c.indexName+"/_search")).timeout(Duration.ofSeconds(10)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));basic(b,c);HttpResponse<String> response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("HTTP "+response.statusCode());Map<String,LinkedHashSet<String>> values=new LinkedHashMap<>();fields.forEach(f->values.put(f,new LinkedHashSet<>()));for(JsonNode hit:json.readTree(response.body()).path("hits").path("hits")){JsonNode document=hit.path("_source");for(String field:fields){JsonNode value=atField(document,field);if(value.isArray())value.forEach(v->{if(v.isValueNode()&&values.get(field).size()<5)values.get(field).add(v.asText());});else if(value.isValueNode()&&values.get(field).size()<5)values.get(field).add(value.asText());}}Map<String,List<String>> result=new LinkedHashMap<>();values.forEach((k,v)->result.put(k,new ArrayList<>(v)));return result;}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(502,"FIELD_SAMPLE_FAILED","字段样本采集失败："+safe(e));}}
 private Map<String,Object> mysql(Config c)throws Exception{String url=c.endpoint;String host=URI.create(url.substring(5)).getHost();allowed(host);Properties p=new Properties();p.setProperty("user",nvl(c.username));p.setProperty("password",nvl(secret(c)));p.setProperty("connectTimeout","5000");try(Connection conn=DriverManager.getConnection(url,p)){DatabaseMetaData md=conn.getMetaData();List<Map<String,Object>> tables=new ArrayList<>();try(ResultSet tr=md.getTables(c.databaseName,null,"%",new String[]{"TABLE","VIEW"})){while(tr.next()){String table=tr.getString("TABLE_NAME");List<Map<String,Object>> cols=new ArrayList<>();try(ResultSet cr=md.getColumns(c.databaseName,null,table,"%")){while(cr.next())cols.add(Map.of("name",cr.getString("COLUMN_NAME"),"type",cr.getString("TYPE_NAME"),"nullable",cr.getInt("NULLABLE")!=DatabaseMetaData.columnNoNulls));}tables.add(Map.of("name",table,"type",tr.getString("TABLE_TYPE"),"columns",cols));}}return Map.of("kind","MYSQL","database",nvl(c.databaseName),"tables",tables);}}
 private Map<String,Object> es(Config c)throws Exception{URI uri=URI.create(c.endpoint);allowed(uri.getHost());HttpRequest.Builder b=HttpRequest.newBuilder(join(uri,c.indexName+"/_mapping")).timeout(Duration.ofSeconds(10)).GET();basic(b,c);HttpResponse<String> r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()/100!=2)throw new IllegalStateException("HTTP "+r.statusCode());JsonNode root=json.readTree(r.body()),props=root.elements().next().path("mappings").path("properties");List<Map<String,Object>> fields=new ArrayList<>();collectEsFields("",props,fields);return Map.of("kind","ELASTICSEARCH","index",c.indexName,"mapping",root,"fields",fields);}
 private void collectEsFields(String prefix,JsonNode properties,List<Map<String,Object>> fields){properties.fields().forEachRemaining(e->{String name=prefix.isEmpty()?e.getKey():prefix+"."+e.getKey(),type=e.getValue().path("type").asText(e.getValue().has("properties")?"object":"keyword");boolean doc=!e.getValue().has("doc_values")||e.getValue().path("doc_values").asBoolean(),scalar=!Set.of("object","nested").contains(type);Map<String,Object> field=new LinkedHashMap<>();field.put("name",name);field.put("type",type);field.put("fullText","text".equals(type));field.put("filterable",scalar&&!"text".equals(type));field.put("sortable",scalar&&doc&&!"text".equals(type));field.put("aggregatable",scalar&&doc&&!"text".equals(type));fields.add(field);if(e.getValue().has("properties"))collectEsFields(name,e.getValue().path("properties"),fields);if(e.getValue().has("fields"))collectEsFields(name,e.getValue().path("fields"),fields);});}
 private void validateEsSemantics(String schemaJson,JsonNode allowedObjects)throws Exception{if(allowedObjects==null||!allowedObjects.path("fields").isArray())throw new BusinessException(422,"FIELD_SCOPE_EMPTY","请至少授权一个字段");Set<String> schemaFields=new LinkedHashSet<>();for(JsonNode field:json.readTree(schemaJson).path("fields"))schemaFields.add(field.path("name").asText());Set<String> selected=new LinkedHashSet<>();for(JsonNode field:allowedObjects.path("fields")){String name=field.asText();if(!schemaFields.contains(name))throw new BusinessException(422,"FIELD_NOT_FOUND","字段不在当前 mapping 中："+name);selected.add(name);}JsonNode semantics=allowedObjects.path("fieldSemantics");if(!semantics.isMissingNode()&&!semantics.isObject())throw new BusinessException(422,"FIELD_SEMANTICS_INVALID","字段语义必须是对象");Iterator<Map.Entry<String,JsonNode>> entries=semantics.fields();while(entries.hasNext()){Map.Entry<String,JsonNode> entry=entries.next();if(!selected.contains(entry.getKey()))throw new BusinessException(422,"FIELD_NOT_AUTHORIZED","不能配置未授权字段的语义："+entry.getKey());for(String purpose:List.of("searchField","filterField","aggregationField","sortField","sourceField")){String actual=entry.getValue().path(purpose).asText("");if(!actual.isBlank()&&!schemaFields.contains(actual))throw new BusinessException(422,"SEMANTIC_TARGET_NOT_FOUND",purpose+" 指向的字段不在当前 mapping 中："+actual);}}}
 private JsonNode atField(JsonNode root,String path){JsonNode current=root;for(String part:path.split("\\.")){current=current.path(part);if(current.isMissingNode())break;}return current;}
 private Config config(UUID id){return jdbc.query("SELECT c.type,v.id,v.endpoint,v.database_name,v.index_name,v.username,v.secret_version_id,v.schema_json,v.allowed_objects_json,v.schema_hash FROM data_source c JOIN data_source_version v ON v.id=c.active_version_id WHERE c.id=?",rs->{if(!rs.next())throw new BusinessException(404,"SOURCE_NOT_FOUND","数据源不存在");return new Config(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10));},id.toString());}
 private void basic(HttpRequest.Builder b,Config c){if(c.username!=null)b.header("Authorization","Basic "+Base64.getEncoder().encodeToString((c.username+":"+nvl(secret(c))).getBytes(StandardCharsets.UTF_8)));}private String secret(Config c){return c.secretId==null?null:secrets.reveal(UUID.fromString(c.secretId),"DATA_SOURCE");}private void allowed(String h){if(!network.allows(h))throw new BusinessException(422,"HOST_NOT_ALLOWED","目标主机不在部署白名单中");}private static URI join(URI b,String p){return URI.create(b.toString().replaceAll("/$","")+"/"+p);}private static String nvl(String s){return s==null?"":s;}private static String hex(byte[] b){return java.util.HexFormat.of().formatHex(b);}private static String safe(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage().replaceAll("(?i)(password|token|key)=[^&\\s]+","$1=***");}
 private record Config(String type,String versionId,String endpoint,String databaseName,String indexName,String username,String secretId,String schemaJson,String allowedJson,String schemaHash){}
 public record Semantics(JsonNode allowedObjects,List<Metric> metrics){} public record SampleRequest(List<String> fields){} public record Metric(String name,String description,JsonNode expression,String timeField,JsonNode filters,String unit,String roundingRule){}
}
