<script setup lang="ts">
import {computed,nextTick,onMounted,ref} from 'vue'
import {ChatDotRound,Plus,Promotion,VideoPause,Search,MoreFilled,Document,Download,DataAnalysis,CircleCheck,Loading,Clock} from '@element-plus/icons-vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,ApiError} from '../api/http'
type Option={id:string;name:string;type?:string};type Conversation={id:string;title:string;model_id:string;source_id:string;source_type:string;knowledge_base_ids?:string[];last_status?:string;updated_at:string}
type Message={id:string;role:'USER'|'ASSISTANT';content:string;sql_text?:string;query_language?:string;result_json?:string;evidence_json?:string;duration_ms?:number;status:string;feedback_rating?:'HELPFUL'|'UNHELPFUL';feedback_comment?:string;task_id?:string;task_stage?:string;created_at:string}
type TaskEvent={sequence_no:number;status:string;stage:string;message:string;occurred_at:string}
const options=ref<{models:Option[];sources:Option[];knowledgeBases:Option[]}>({models:[],sources:[],knowledgeBases:[]}),conversations=ref<Conversation[]>([]),messages=ref<Message[]>([]),history=ref<TaskEvent[]>([])
const currentId=ref(''),modelId=ref(''),sourceId=ref(''),knowledgeBaseIds=ref<string[]>([]),question=ref(''),sending=ref(false),taskId=ref(''),stage=ref(''),searchText=ref(''),messagePanel=ref<HTMLElement>(),drawer=ref(false),evidenceMessage=ref<Message|null>(null)
let stream:EventSource|null=null
const stageOrder=['UNDERSTANDING','GENERATING_QUERY','QUERYING','REPAIRING_QUERY','RETRIEVING_KNOWLEDGE','GENERATING_ANSWER','COMPLETED'];const stageText:Record<string,string>={QUEUED:'任务已提交',UNDERSTANDING:'理解问题与会话上下文',CLARIFICATION:'等待补充分析条件',GENERATING_QUERY:'生成并校验受控查询',QUERYING:'执行查询并获取证据',REPAIRING_QUERY:'根据执行错误修正查询',RETRIEVING_KNOWLEDGE:'检索知识库与校验引用',GENERATING_ANSWER:'生成可核查结论',ANSWER_FALLBACK:'保留结果并生成基础说明',COMPLETED:'分析完成',FAILED:'分析失败',CANCELLED:'任务已停止'}
const selectedSource=computed(()=>options.value.sources.find(x=>x.id===sourceId.value)),selectedModel=computed(()=>options.value.models.find(x=>x.id===modelId.value)),canSend=computed(()=>question.value.trim()&&modelId.value&&sourceId.value&&!sending.value)
const filteredConversations=computed(()=>conversations.value.filter(x=>x.title.toLowerCase().includes(searchText.value.trim().toLowerCase())))
const examples=computed(()=>selectedSource.value?.type==='ELASTICSEARCH'?['统计昨天不同错误类型的日志数量','查找最近一小时响应最慢的请求','按服务名称汇总近 7 天告警']:['统计上个月各地区销售额','筛选退款率超过 5% 的商品品类','分析近 30 天订单量和客单价趋势'])
const currentStageIndex=computed(()=>stageOrder.indexOf(stage.value));
async function initialize(){try{options.value=await api('/api/v1/chat/options');if(options.value.models.length)modelId.value=options.value.models[0].id;if(options.value.sources.length)sourceId.value=options.value.sources[0].id;await loadConversations()}catch(e){showError(e,'加载问答配置失败')}}
async function loadConversations(){conversations.value=await api('/api/v1/chat/conversations')}
async function openConversation(row:Conversation){stream?.close();currentId.value=row.id;modelId.value=row.model_id;sourceId.value=row.source_id;knowledgeBaseIds.value=row.knowledge_base_ids??[];await loadMessages();const last=[...messages.value].reverse().find(x=>x.task_id);if(last?.task_id){taskId.value=last.task_id;stage.value=last.task_stage||last.status;await loadHistory(last.task_id)}}
async function loadMessages(){if(!currentId.value){messages.value=[];return}messages.value=await api(`/api/v1/chat/conversations/${currentId.value}/messages`);await nextTick();messagePanel.value?.scrollTo({top:messagePanel.value.scrollHeight,behavior:'smooth'})}
async function loadHistory(id:string){history.value=await api(`/api/v1/chat/tasks/${id}/history`)}
function newConversation(){stream?.close();currentId.value='';messages.value=[];history.value=[];taskId.value='';stage.value='';knowledgeBaseIds.value=[]}
async function ensureConversation(){if(currentId.value)return currentId.value;const created=await api<{id:string}>('/api/v1/chat/conversations',{method:'POST',body:JSON.stringify({modelId:modelId.value,sourceId:sourceId.value,knowledgeBaseIds:knowledgeBaseIds.value})});currentId.value=created.id;await loadConversations();return created.id}
async function send(){if(!canSend.value)return;const content=question.value.trim();sending.value=true;stage.value='QUEUED';history.value=[];try{const id=await ensureConversation();question.value='';const result=await api<{taskId:string}>(`/api/v1/chat/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({content})});taskId.value=result.taskId;await loadMessages();watchTask(result.taskId);await loadConversations()}catch(e){sending.value=false;stage.value='';showError(e,'问题提交失败')}}
function watchTask(id:string){stream?.close();stream=new EventSource(`/api/v1/chat/tasks/${id}/events`);stream.addEventListener('progress',async event=>{const data=JSON.parse((event as MessageEvent).data);stage.value=data.stage;await loadHistory(id);if(['COMPLETED','FAILED','CANCELLED'].includes(data.status)){stream?.close();sending.value=false;await loadMessages();await loadConversations();if(data.status==='FAILED')ElMessage.error(data.message||'分析失败')}});stream.onerror=()=>{stream?.close();pollTask(id)}}
async function pollTask(id:string){try{const task=await api<any>(`/api/v1/chat/tasks/${id}`);stage.value=task.stage;await loadHistory(id);if(['COMPLETED','FAILED','CANCELLED'].includes(task.status)){sending.value=false;await loadMessages()}else setTimeout(()=>pollTask(id),1500)}catch{sending.value=false}}
async function cancel(){if(!taskId.value)return;await api(`/api/v1/chat/tasks/${taskId.value}/cancel`,{method:'POST'});stage.value='CANCELLED'}
async function conversationAction(command:string,row:Conversation){if(command==='rename'){try{const {value}=await ElMessageBox.prompt('输入新的会话标题','重命名会话',{inputValue:row.title,inputPattern:/\S+/,inputErrorMessage:'标题不能为空'});await api(`/api/v1/chat/conversations/${row.id}`,{method:'PUT',body:JSON.stringify({title:value})});await loadConversations()}catch(e){if(e!=='cancel'&&e!=='close')showError(e,'重命名失败')}}else{try{await ElMessageBox.confirm('删除后将无法查看消息、执行记录和下载文件。','删除会话',{type:'warning',confirmButtonText:'确认删除会话',cancelButtonText:'取消'});await api(`/api/v1/chat/conversations/${row.id}`,{method:'DELETE'});if(currentId.value===row.id)newConversation();await loadConversations()}catch(e){if(e!=='cancel'&&e!=='close')showError(e,'删除失败')}}}
function resultRows(message:Message):Record<string,unknown>[]{try{return message.result_json?JSON.parse(message.result_json):[]}catch{return[]}}function resultColumns(message:Message){const rows=resultRows(message);return rows.length?Object.keys(rows[0]):[]}
function formatAnswer(value:string){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function chartSpec(message:Message){const rows=resultRows(message).filter(row=>!('aggregations' in row));if(rows.length<2)return null;const columns=Object.keys(rows[0]),valueKey=columns.find(key=>typeof rows[0][key]==='number'),labelKey=columns.find(key=>key!==valueKey);if(!valueKey||!labelKey)return null;const items=rows.slice(0,8).map(row=>({label:String(row[labelKey]??''),value:Number(row[valueKey]??0)})),max=Math.max(...items.map(x=>Math.abs(x.value)),1);return{valueKey,labelKey,items,max}}
function openEvidence(message:Message){evidenceMessage.value=message;drawer.value=true}function evidence(){try{return evidenceMessage.value?.evidence_json?JSON.parse(evidenceMessage.value.evidence_json):{}}catch{return{}}}
async function download(message:Message,format:'csv'|'md'){const response=await fetch(`/api/v1/chat/messages/${message.id}/export.${format}`,{credentials:'same-origin'});if(!response.ok){ElMessage.error('导出失败');return}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=format==='csv'?'analysis-result.csv':'analysis-report.md';a.click();URL.revokeObjectURL(url)}
async function feedback(message:Message,rating:'HELPFUL'|'UNHELPFUL'){let comment='';if(rating==='UNHELPFUL')try{const result=await ElMessageBox.prompt('哪些内容不准确或没有解决问题？','帮助我们改进',{inputType:'textarea',inputPlaceholder:'可选，最多 500 字',inputValidator:v=>!v||v.length<=500||'不能超过 500 字',confirmButtonText:'提交'});comment=result.value}catch(e){if(e==='cancel'||e==='close')return}await api(`/api/v1/chat/messages/${message.id}/feedback`,{method:'PUT',body:JSON.stringify({rating,comment})});message.feedback_rating=rating;message.feedback_comment=comment;ElMessage.success('感谢反馈')}
function eventState(item:TaskEvent){if(item.status==='FAILED')return'danger';if(item.status==='CANCELLED')return'warning';return item.stage===stage.value&&sending.value?'primary':'success'}
function showError(e:unknown,fallback:string){ElMessage.error(e instanceof ApiError?e.message:fallback)}
onMounted(initialize)
</script>
<template><div class="analysis-workspace">
 <aside class="session-rail"><div class="session-head"><h2>分析会话 <el-tag size="small" effect="plain">{{conversations.length}}</el-tag></h2><el-button type="primary" :icon="Plus" @click="newConversation">新建分析会话</el-button><el-input v-model="searchText" :prefix-icon="Search" placeholder="搜索历史会话" clearable/></div><div class="session-list"><div class="session-group">最近会话</div><div v-for="item in filteredConversations" :key="item.id" :class="['session-row',{active:item.id===currentId}]" @click="openConversation(item)"><span :class="['status-dot',(item.last_status||'idle').toLowerCase()]"/><div><strong>{{item.title}}</strong><small>{{item.source_type}} · {{item.last_status==='RUNNING'?'执行中':item.last_status==='FAILED'?'失败':'已归档'}}</small></div><el-dropdown trigger="click" @command="(command:string)=>conversationAction(command,item)" @click.stop><el-button link :icon="MoreFilled"/><template #dropdown><el-dropdown-menu><el-dropdown-item command="rename">重命名</el-dropdown-item><el-dropdown-item command="delete" divided>删除会话</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><el-empty v-if="!filteredConversations.length" description="暂无匹配会话" :image-size="52"/></div></aside>
 <main class="analysis-main"><header class="analysis-config"><div class="config-select"><span>模型</span><el-select v-model="modelId" :disabled="!!currentId" placeholder="选择模型"><el-option v-for="x in options.models" :key="x.id" :label="x.name" :value="x.id"/></el-select></div><div class="config-select"><span>数据源</span><el-select v-model="sourceId" :disabled="!!currentId" placeholder="选择数据源"><el-option v-for="x in options.sources" :key="x.id" :label="`${x.name}（${x.type}）`" :value="x.id"/></el-select></div><div class="config-select"><span>知识库</span><el-select v-model="knowledgeBaseIds" multiple collapse-tags collapse-tags-tooltip :max-collapse-tags="1" :disabled="!!currentId" placeholder="可选，最多 5 个"><el-option v-for="x in options.knowledgeBases" :key="x.id" :label="x.name" :value="x.id" :disabled="knowledgeBaseIds.length>=5&&!knowledgeBaseIds.includes(x.id)"/></el-select></div><el-button v-if="currentId" link type="primary" @click="newConversation">新建会话以更换配置</el-button></header>
  <div ref="messagePanel" class="analysis-messages"><section v-if="!messages.length" class="analysis-welcome"><div class="welcome-icon"><ChatDotRound/></div><h1>今天想分析什么业务数据？</h1><p>选择模型和数据源，使用自然语言提问。系统会展示实际执行的查询、证据和结论。</p><div class="example-caption">基于当前 {{selectedSource?.type||'数据源'}} 的推荐分析场景</div><button v-for="example in examples" :key="example" @click="question=example"><DataAnalysis/>{{example}}<span>↗</span></button><el-alert v-if="!options.models.length||!options.sources.length" type="warning" :closable="false" title="需要先启用至少一个对话模型和已发布数据源"/></section>
   <template v-for="message in messages" :key="message.id"><div v-if="message.role==='USER'" class="question-row"><div class="question-bubble">{{message.content}}</div><div class="user-avatar">你</div></div><article v-else class="answer-report"><header><div class="assistant-mark">AI</div><div><strong>智能数据分析助手</strong><small v-if="message.status==='COMPLETED'"><CircleCheck/> 已完成 · {{message.duration_ms}} ms</small><small v-else-if="message.status==='FAILED'" class="failed">执行失败</small><small v-else><Loading class="spin"/> 正在分析</small></div></header><div class="report-body"><h3 v-if="message.status==='COMPLETED'">{{message.query_language?'核心分析结论':'需要补充信息'}}</h3><p v-html="formatAnswer(message.content)"/><el-skeleton v-if="!message.content&&message.status==='RUNNING'" :rows="4" animated/><div v-if="resultRows(message).length" class="result-preview"><div class="result-title"><span><Document/> 数据结果概览</span><small>共 {{resultRows(message).length}} 行{{resultRows(message).length>=200?'（已截断）':''}}</small></div><el-table :data="resultRows(message).slice(0,5)" border><el-table-column v-for="column in resultColumns(message)" :key="column" :prop="column" :label="column" min-width="130" show-overflow-tooltip/></el-table><div v-if="chartSpec(message)" class="mini-chart"><div class="result-title"><span><DataAnalysis/> {{chartSpec(message)?.valueKey}} 分布</span></div><div v-for="item in chartSpec(message)?.items" :key="item.label" class="chart-row"><label>{{item.label}}</label><div><i :style="{width:`${Math.abs(item.value)/chartSpec(message)!.max*100}%`}"/></div><strong>{{item.value}}</strong></div></div></div></div><footer v-if="message.status==='COMPLETED'"><template v-if="message.query_language"><el-button :icon="Document" @click="openEvidence(message)">查看证据与{{message.query_language}}</el-button><el-button :icon="Download" @click="download(message,'csv')">导出 CSV</el-button><el-button :icon="Download" @click="download(message,'md')">导出报告</el-button></template><span style="margin-left:auto;color:#909399">回答是否有帮助？</span><el-button :type="message.feedback_rating==='HELPFUL'?'primary':''" text @click="feedback(message,'HELPFUL')">有帮助</el-button><el-button :type="message.feedback_rating==='UNHELPFUL'?'danger':''" text @click="feedback(message,'UNHELPFUL')">需改进</el-button></footer></article></template>
  </div><footer class="analysis-composer"><div v-if="currentId" class="locked-context">当前已锁定：{{selectedModel?.name}} · {{selectedSource?.name}}（{{selectedSource?.type}}）<template v-if="knowledgeBaseIds.length"> · {{knowledgeBaseIds.length}} 个知识库</template></div><div v-if="sending" class="running-strip"><Clock/> {{stageText[stage]||stage}}<el-button link type="danger" :icon="VideoPause" @click="cancel">停止任务</el-button></div><el-input v-model="question" type="textarea" resize="none" :autosize="{minRows:3,maxRows:6}" maxlength="4000" placeholder="请输入想分析的业务问题，尽量说明时间范围、指标和筛选条件…" @keydown.ctrl.enter="send"/><div><span>Ctrl + Enter 发送 · 查询结果最多 200 行</span><el-button type="primary" :icon="Promotion" :loading="sending" :disabled="!canSend" @click="send">开始分析</el-button></div></footer></main>
 <aside class="process-rail"><header><h3>执行过程与审计</h3><el-tag v-if="sending" type="success" size="small">实时</el-tag></header><div v-if="!history.length" class="process-empty"><Clock/><strong>等待发起查询任务</strong><p>提交问题后，这里会展示可审计的执行步骤。</p></div><el-timeline v-else><el-timeline-item v-for="item in history" :key="item.sequence_no" :type="eventState(item)" :hollow="eventState(item)==='primary'" :timestamp="item.message"><strong>{{stageText[item.stage]||item.stage}}</strong></el-timeline-item></el-timeline><div class="safety-note">✓ 所有查询均经过授权范围校验并保留审计记录</div></aside>
 <el-drawer v-model="drawer" title="证据详情" size="680px"><template v-if="evidenceMessage"><div class="evidence-summary"><el-tag>{{evidenceMessage.query_language}}</el-tag><strong>{{evidence().sourceName}}</strong><span>返回 {{evidence().returnedRows??0}} 行</span><span>执行 {{evidence().executionMs??evidence().tookMs??0}} ms</span></div><h3>实际执行的{{evidenceMessage.query_language==='DSL'?' Elasticsearch DSL':'只读 SQL'}}</h3><pre class="evidence-code">{{evidenceMessage.sql_text}}</pre><el-alert v-if="evidence().partialFailure" type="warning" :closable="false" title="知识库检索失败，本回答已使用结构化数据降级完成"/><template v-if="evidence().citations?.length"><h3>知识库引用</h3><div v-for="(citation,index) in evidence().citations" :key="citation.chunk_id" style="padding:12px;margin-bottom:10px;border:1px solid #e5e7eb;border-radius:8px"><strong>[{{Number(index)+1}}] {{citation.document_name}}<template v-if="citation.page_number"> · 第 {{citation.page_number}} 页</template></strong><p style="margin:8px 0;color:#475569;line-height:1.6">{{citation.content}}</p><small style="color:#909399">{{citation.knowledge_name}} · 相似度 {{Number(citation.score??0).toFixed(3)}}</small></div></template><div class="drawer-actions"><el-button :icon="Download" @click="download(evidenceMessage,'csv')">下载完整 CSV</el-button><el-button :icon="Download" @click="download(evidenceMessage,'md')">下载 Markdown 报告</el-button></div><h3>结果集预览</h3><el-table :data="resultRows(evidenceMessage).slice(0,20)" border max-height="420"><el-table-column v-for="column in resultColumns(evidenceMessage)" :key="column" :prop="column" :label="column" min-width="140" show-overflow-tooltip/></el-table><el-alert v-if="evidence().truncated" type="warning" :closable="false" title="结果已按平台限制截断为 200 行"/></template></el-drawer>
</div></template>
