<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue';import {useRoute} from 'vue-router';import {ElMessage,ElMessageBox} from 'element-plus';import {api,ApiError} from '../api/http'
const route=useRoute(),rows=ref<Record<string,any>[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false)
const editingId=ref('')
const scopeDialog=ref(false),scopeLoading=ref(false),scopeSaving=ref(false),sampleLoading=ref(false),currentSource=ref<Record<string,any>|null>(null),scopeItems=ref<any[]>([]),selectedScope=ref<string[]>([]),fieldSemantics=ref<Record<string,any>>({})
const catalog=computed(()=>String(route.meta.catalog)),title=computed(()=>String(route.meta.title)),isModel=computed(()=>['models','embedding-models'].includes(catalog.value)),isSource=computed(()=>catalog.value==='data-sources')
const form=reactive({displayName:'',provider:'OPENAI',endpoint:'',modelName:'',apiKey:'',timeoutMs:30000,name:'',type:'MYSQL',databaseName:'',indexName:'',username:'',password:'',timezone:'Asia/Shanghai',purpose:'',description:'',embeddingId:''})
async function load(){loading.value=true;try{rows.value=await api(`/api/v1/admin/${catalog.value}`)}finally{loading.value=false}}
function resetForm(){Object.assign(form,{displayName:'',provider:'OPENAI',endpoint:'',modelName:'',apiKey:'',timeoutMs:30000,name:'',type:'MYSQL',databaseName:'',indexName:'',username:'',password:'',timezone:'Asia/Shanghai',purpose:'',description:'',embeddingId:''})}
function openCreate(){editingId.value='';resetForm();dialog.value=true}
function editModel(row:any){editingId.value=row.id;Object.assign(form,{displayName:row.display_name,provider:row.provider,endpoint:row.endpoint,modelName:row.model_name,apiKey:'',timeoutMs:row.timeout_ms});dialog.value=true}
async function removeModel(row:any){try{await ElMessageBox.confirm(`确定删除模型“${row.display_name}”吗？删除后无法恢复。`,'删除模型',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await api(`/api/v1/admin/${catalog.value}/${row.id}`,{method:'DELETE'});ElMessage.success('模型已删除');await load()}catch(e){if(e==='cancel'||e==='close')return;ElMessage.error(e instanceof ApiError?e.message:'删除失败')}}
async function create(){saving.value=true;try{let body:any;if(isModel.value)body={displayName:form.displayName,provider:form.provider,endpoint:form.endpoint,modelName:form.modelName,apiKey:form.apiKey||null,timeoutMs:form.timeoutMs};else if(isSource.value)body={name:form.name,type:form.type,endpoint:form.endpoint,databaseName:form.databaseName||null,indexName:form.indexName||null,username:form.username||null,password:form.password||null,timezone:form.timezone,purpose:form.purpose};else body={name:form.name,description:form.description,embeddingId:form.embeddingId||null};const path=editingId.value?`/api/v1/admin/${catalog.value}/${editingId.value}`:`/api/v1/admin/${catalog.value}`;await api(path,{method:editingId.value?'PUT':'POST',body:JSON.stringify(body)});dialog.value=false;ElMessage.success(editingId.value?'模型已修改，请重新测试后启用':'配置已创建');await load()}catch(e){ElMessage.error(e instanceof ApiError?e.message:(editingId.value?'修改失败':'创建失败'))}finally{saving.value=false}}
async function test(row:any){try{const r=await api<any>(`/api/v1/admin/${catalog.value}/${row.id}/tests`,{method:'POST'});ElMessage.success(`${r.message}（${r.elapsedMs} ms）`)}catch(e){ElMessage.error(e instanceof ApiError?e.message:'测试失败')}finally{await load()}}
async function configureScope(row:any){currentSource.value=row;scopeDialog.value=true;scopeLoading.value=true;scopeItems.value=[];selectedScope.value=[];fieldSemantics.value={};try{await api(`/api/v1/admin/data-sources/${row.id}/schema-refresh`,{method:'POST'});const data=await api<any>(`/api/v1/admin/data-sources/${row.id}/schema`);if(row.type==='MYSQL'){scopeItems.value=(data.schema.tables??[]).map((table:any)=>({name:table.name,detail:`${table.type} · ${(table.columns??[]).length} 个字段`}));selectedScope.value=data.allowedObjects?.tables??[]}else{scopeItems.value=(data.schema.fields??[]).map((field:any)=>({...field,detail:field.type}));selectedScope.value=data.allowedObjects?.fields??[];for(const field of scopeItems.value){const saved=data.allowedObjects?.fieldSemantics?.[field.name]??{};fieldSemantics.value[field.name]={displayName:saved.displayName??'',description:saved.description??'',synonyms:Array.isArray(saved.synonyms)?saved.synonyms.join('，'):'',examples:Array.isArray(saved.examples)?saved.examples:[],searchField:saved.searchField??field.name,filterField:saved.filterField??field.name,aggregationField:saved.aggregationField??field.name,sortField:saved.sortField??field.name,sourceField:saved.sourceField??field.name,fullText:saved.fullText??field.fullText,filterable:saved.filterable??field.filterable,aggregatable:saved.aggregatable??field.aggregatable,sortable:saved.sortable??field.sortable,type:field.type}}}ElMessage.success('结构刷新成功，请配置授权范围和字段语义')}catch(e){scopeDialog.value=false;ElMessage.error(e instanceof ApiError?e.message:'结构刷新失败')}finally{scopeLoading.value=false}}
async function collectSamples(){if(!currentSource.value||selectedScope.value.length===0){ElMessage.warning('请先选择需要采样的字段');return}sampleLoading.value=true;try{const samples=await api<Record<string,string[]>>(`/api/v1/admin/data-sources/${currentSource.value.id}/field-samples`,{method:'POST',body:JSON.stringify({fields:selectedScope.value})});for(const [name,values] of Object.entries(samples))fieldSemantics.value[name].examples=values;ElMessage.success('字段样本采集完成')}catch(e){ElMessage.error(e instanceof ApiError?e.message:'样本采集失败')}finally{sampleLoading.value=false}}
function selectAllScope(){selectedScope.value=scopeItems.value.map(item=>item.name)}
function clearAllScope(){selectedScope.value=[]}
async function saveScope(){if(!currentSource.value)return;if(selectedScope.value.length===0){ElMessage.warning('请至少选择一项授权范围');return}scopeSaving.value=true;try{const key=currentSource.value.type==='MYSQL'?'tables':'fields';const allowedObjects:any={[key]:selectedScope.value};if(currentSource.value.type==='ELASTICSEARCH'){allowedObjects.fieldSemantics={};for(const name of selectedScope.value){const item=fieldSemantics.value[name];allowedObjects.fieldSemantics[name]={...item,synonyms:String(item.synonyms??'').split(/[，,]/).map((v:string)=>v.trim()).filter(Boolean)}}}await api(`/api/v1/admin/data-sources/${currentSource.value.id}/semantics`,{method:'PUT',body:JSON.stringify({allowedObjects,metrics:[]})});scopeDialog.value=false;ElMessage.success('授权范围与字段语义已保存，现在可以发布数据源')}catch(e){ElMessage.error(e instanceof ApiError?e.message:'字段语义保存失败')}finally{scopeSaving.value=false}}
async function toggle(row:any){const action=row.enabled?'disable':isSource.value?'publish':'enable';try{await api(`/api/v1/admin/${catalog.value}/${row.id}/${action}`,{method:'POST'});ElMessage.success(row.enabled?'已停用':'已启用')}catch(e){ElMessage.error(e instanceof ApiError?e.message:'操作失败')}finally{await load()}}
watch(catalog,load);onMounted(load)
</script>
<template><section class="page-card"><div class="page-toolbar"><div><h2>{{title}}</h2><p>{{catalog==='embedding-models'?'用于知识库向量化，不用于生成对话答案':'创建、测试并启用平台配置'}}</p></div><el-button type="primary" @click="openCreate">新建配置</el-button></div>
<el-table v-loading="loading" :data="rows"><el-table-column :prop="isModel?'display_name':'name'" label="名称" min-width="170"/><el-table-column v-if="isModel" prop="provider" label="供应商" width="110"/><el-table-column v-if="isSource" prop="type" label="类型" width="130"/><el-table-column v-if="catalog!=='knowledge-bases'" prop="endpoint" label="服务地址" min-width="230" show-overflow-tooltip/><el-table-column v-if="isModel" prop="model_name" label="模型" min-width="150"/><el-table-column v-if="catalog!=='knowledge-bases'" label="测试状态" width="120"><template #default="{row}"><el-tag :type="row.test_status==='PASSED'?'success':row.test_status==='FAILED'?'danger':'info'">{{row.test_status}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'已启用':'未启用'}}</el-tag></template></el-table-column><el-table-column v-if="catalog!=='knowledge-bases'" label="操作" :width="isSource?250:isModel?280:170"><template #default="{row}"><el-button link type="primary" @click="test(row)">测试</el-button><el-button v-if="isSource" link type="primary" :disabled="row.test_status!=='PASSED'" @click="configureScope(row)">结构与范围</el-button><el-button link :type="row.enabled?'danger':'primary'" @click="toggle(row)">{{row.enabled?'停用':isSource?'发布':'启用'}}</el-button><el-button v-if="isModel" link type="primary" @click="editModel(row)">修改</el-button><el-button v-if="isModel" link type="danger" @click="removeModel(row)">删除</el-button></template></el-table-column></el-table></section>
<el-dialog v-model="dialog" :title="editingId?`修改${title}`:`新建${title}`" width="560px"><el-form label-position="top"><template v-if="isModel"><el-form-item label="配置名称"><el-input v-model="form.displayName"/></el-form-item><el-form-item label="供应商"><el-select v-model="form.provider" style="width:100%"><el-option label="OpenAI 兼容" value="OPENAI"/><el-option label="Ollama" value="OLLAMA"/></el-select></el-form-item><el-form-item label="服务地址"><el-input v-model="form.endpoint" placeholder="https://example.com/v1"/></el-form-item><el-form-item label="模型名称"><el-input v-model="form.modelName"/></el-form-item><el-form-item :label="editingId?'API Key（留空则保留原凭证）':'API Key（Ollama 可留空）'"><el-input v-model="form.apiKey" type="password" show-password/></el-form-item><el-form-item label="超时时间（毫秒）"><el-input-number v-model="form.timeoutMs" :min="1000" :max="120000" :step="1000" style="width:100%"/></el-form-item><el-alert v-if="editingId" type="warning" :closable="false" title="保存修改后模型会自动停用，需要重新测试并启用。"/></template><template v-else-if="isSource"><el-form-item label="数据源名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.type"><el-radio value="MYSQL">MySQL</el-radio><el-radio value="ELASTICSEARCH">Elasticsearch</el-radio></el-radio-group></el-form-item><el-form-item label="连接地址"><el-input v-model="form.endpoint" :placeholder="form.type==='MYSQL'?'jdbc:mysql://host:3306/database':'http://host:9200'"/></el-form-item><el-form-item v-if="form.type==='MYSQL'" label="数据库名"><el-input v-model="form.databaseName"/></el-form-item><el-form-item v-else label="具体索引名"><el-input v-model="form.indexName"/></el-form-item><el-form-item label="用户名"><el-input v-model="form.username"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item label="业务用途"><el-input v-model="form.purpose" type="textarea"/></el-form-item></template><template v-else><el-form-item label="知识库名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="用途说明"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item label="Embedding 配置 ID"><el-input v-model="form.embeddingId" placeholder="选择器将在文档链路阶段接入"/></el-form-item></template></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">{{editingId?'保存修改':'创建'}}</el-button></template></el-dialog>
<el-dialog v-model="scopeDialog" title="结构、授权范围与字段语义" :width="currentSource?.type==='ELASTICSEARCH'?'1100px':'620px'">
  <div v-loading="scopeLoading">
    <el-alert type="info" :closable="false" :title="currentSource?.type==='ELASTICSEARCH'?'字段语义将用于模型选择字段，搜索、筛选、聚合和排序字段会由后端按用途替换并校验。':'请选择允许平台查询的表；这里不会检查 MySQL 账号是否只读。'"/>
    <template v-if="currentSource?.type==='ELASTICSEARCH'">
      <div style="display:flex;justify-content:space-between;margin:14px 0 10px"><div><el-button :disabled="selectedScope.length===scopeItems.length" @click="selectAllScope">全选</el-button><el-button :disabled="selectedScope.length===0" @click="clearAllScope">取消全选</el-button><span style="margin-left:12px;color:#909399">已选择 {{selectedScope.length}} / {{scopeItems.length}}</span></div><el-button :loading="sampleLoading" @click="collectSamples">采集已选字段样本</el-button></div>
      <el-table :data="scopeItems" max-height="500" size="small">
        <el-table-column label="授权" width="64"><template #default="{row}"><el-checkbox v-model="selectedScope" :value="row.name"/></template></el-table-column>
        <el-table-column prop="name" label="ES 字段" min-width="150" show-overflow-tooltip><template #default="{row}"><div>{{row.name}}</div><small style="color:#909399">{{row.type}} · {{row.fullText?'全文检索 ':''}}{{row.aggregatable?'可聚合 ':''}}{{row.sortable?'可排序':''}}</small></template></el-table-column>
        <el-table-column label="中文名称" width="130"><template #default="{row}"><el-input v-model="fieldSemantics[row.name].displayName" :disabled="!selectedScope.includes(row.name)" placeholder="如：发布站点"/></template></el-table-column>
        <el-table-column label="业务说明" min-width="190"><template #default="{row}"><el-input v-model="fieldSemantics[row.name].description" :disabled="!selectedScope.includes(row.name)" placeholder="字段表示的业务含义"/></template></el-table-column>
        <el-table-column label="同义词" min-width="160"><template #default="{row}"><el-input v-model="fieldSemantics[row.name].synonyms" :disabled="!selectedScope.includes(row.name)" placeholder="站点，媒体，网站"/></template></el-table-column>
        <el-table-column label="聚合字段" min-width="160"><template #default="{row}"><el-input v-model="fieldSemantics[row.name].aggregationField" :disabled="!selectedScope.includes(row.name)" placeholder="如：site.keyword"/></template></el-table-column>
        <el-table-column label="样本值" min-width="170"><template #default="{row}"><span style="color:#606266">{{(fieldSemantics[row.name].examples??[]).slice(0,3).join('、')||'尚未采集'}}</span></template></el-table-column>
      </el-table>
    </template>
    <template v-else><div style="display:flex;align-items:center;margin:14px 0 10px"><el-button :disabled="selectedScope.length===scopeItems.length" @click="selectAllScope">全选</el-button><el-button :disabled="selectedScope.length===0" @click="clearAllScope">取消全选</el-button><span style="margin-left:12px;color:#909399">已选择 {{selectedScope.length}} / {{scopeItems.length}}</span></div><el-checkbox-group v-model="selectedScope" style="display:grid;grid-template-columns:1fr 1fr;gap:10px;max-height:420px;overflow:auto"><el-checkbox v-for="item in scopeItems" :key="item.name" :value="item.name" border><span>{{item.name}}</span><small style="margin-left:8px;color:#909399">{{item.detail}}</small></el-checkbox></el-checkbox-group></template>
    <el-empty v-if="!scopeLoading&&scopeItems.length===0" description="未发现可授权的结构"/>
  </div>
  <template #footer><el-button @click="scopeDialog=false">取消</el-button><el-button type="primary" :loading="scopeSaving" :disabled="scopeLoading" @click="saveScope">保存授权范围与语义</el-button></template>
</el-dialog></template>
