<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,ApiError} from '../api/http'
const rows=ref<any[]>([]),embeddings=ref<any[]>([]),loading=ref(false),createDialog=ref(false),detailDialog=ref(false),saving=ref(false),uploading=ref(false),current=ref<any>(),documents=ref<any[]>([]),generations=ref<any[]>([])
const form=reactive({name:'',description:'',embeddingId:''})
function error(e:unknown,text:string){ElMessage.error(e instanceof ApiError?e.message:text)}
async function load(){loading.value=true;try{[rows.value,embeddings.value]=await Promise.all([api<any[]>('/api/v1/admin/knowledge-bases'),api<any[]>('/api/v1/admin/embedding-models')])}finally{loading.value=false}}
async function create(){saving.value=true;try{await api('/api/v1/admin/knowledge-bases',{method:'POST',body:JSON.stringify(form)});createDialog.value=false;Object.assign(form,{name:'',description:'',embeddingId:''});ElMessage.success('知识库已创建');await load()}catch(e){error(e,'创建失败')}finally{saving.value=false}}
async function open(row:any){current.value=row;detailDialog.value=true;await loadDetail()}
async function loadDetail(){if(!current.value)return;[documents.value,generations.value]=await Promise.all([api<any[]>(`/api/v1/admin/knowledge-bases/${current.value.id}/documents`),api<any[]>(`/api/v1/admin/knowledge-bases/${current.value.id}/generations`)])}
async function upload(file:any){if(!current.value)return;uploading.value=true;try{const data=new FormData();data.append('file',file.raw);await api(`/api/v1/admin/knowledge-bases/${current.value.id}/documents`,{method:'POST',body:data});ElMessage.success('文档已提交解析');setTimeout(loadDetail,800)}catch(e){error(e,'上传失败')}finally{uploading.value=false}}
async function removeDocument(row:any){try{await ElMessageBox.confirm(`确定移除“${row.normalized_name}”吗？`,'移除文档',{type:'warning'});await api(`/api/v1/admin/documents/${row.id}`,{method:'DELETE'});await loadDetail()}catch(e){if(e!=='cancel'&&e!=='close')error(e,'移除失败')}}
async function reindex(){try{await api(`/api/v1/admin/knowledge-bases/${current.value.id}/reindex`,{method:'POST'});ElMessage.success('索引任务已开始');setTimeout(loadDetail,1000)}catch(e){error(e,'索引启动失败')}}
async function toggle(row:any){try{await api(`/api/v1/admin/knowledge-bases/${row.id}/${row.enabled?'disable':'enable'}`,{method:'POST'});ElMessage.success(row.enabled?'知识库已停用':'知识库已启用');await load()}catch(e){error(e,'操作失败')}}
onMounted(load)
</script>
<template><section class="page-card"><div class="page-toolbar"><div><h2>知识库</h2><p>管理文档、向量索引和问答引用来源</p></div><el-button type="primary" @click="createDialog=true">新建知识库</el-button></div>
<el-table v-loading="loading" :data="rows"><el-table-column prop="name" label="名称" min-width="170"/><el-table-column prop="description" label="说明" min-width="240" show-overflow-tooltip/><el-table-column prop="embedding_name" label="Embedding 模型" min-width="160"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'已启用':'未启用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="210"><template #default="{row}"><el-button link type="primary" @click="open(row)">文档与索引</el-button><el-button link :type="row.enabled?'danger':'primary'" @click="toggle(row)">{{row.enabled?'停用':'启用'}}</el-button></template></el-table-column></el-table></section>
<el-dialog v-model="createDialog" title="新建知识库" width="560px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="用途说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="Embedding 模型"><el-select v-model="form.embeddingId" style="width:100%" placeholder="选择已启用模型"><el-option v-for="item in embeddings.filter(x=>x.enabled)" :key="item.id" :label="item.display_name" :value="item.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog>
<el-dialog v-model="detailDialog" :title="`${current?.name??''} · 文档与索引`" width="900px"><div class="page-toolbar"><div><strong>文档</strong><p>支持 PDF、DOCX、TXT，解析完成后重建向量索引</p></div><el-upload :show-file-list="false" :auto-upload="false" :on-change="upload" accept=".pdf,.docx,.txt"><el-button type="primary" :loading="uploading">上传文档</el-button></el-upload></div><el-table :data="documents" max-height="280"><el-table-column prop="normalized_name" label="文件" min-width="220"/><el-table-column prop="version_no" label="版本" width="75"/><el-table-column label="解析状态" width="110"><template #default="{row}"><el-tag :type="row.parse_status==='PARSED'?'success':row.parse_status==='FAILED'?'danger':'warning'">{{row.parse_status}}</el-tag></template></el-table-column><el-table-column prop="page_count" label="页数" width="75"/><el-table-column label="操作" width="80"><template #default="{row}"><el-button link type="danger" @click="removeDocument(row)">移除</el-button></template></el-table-column></el-table><div class="page-toolbar" style="margin-top:20px"><div><strong>索引代次</strong><p>新代次完整写入后自动切换，旧索引在此之前继续可用</p></div><el-button type="primary" @click="reindex">重建索引</el-button></div><el-table :data="generations" max-height="220"><el-table-column prop="generation_no" label="代次" width="75"/><el-table-column prop="status" label="状态" width="120"/><el-table-column prop="document_count" label="文档" width="75"/><el-table-column prop="chunk_count" label="片段" width="75"/><el-table-column prop="failure_code" label="失败原因" min-width="180"/></el-table></el-dialog></template>
