package com.agentplatform.chat;

import com.agentplatform.common.BusinessException;
import com.agentplatform.identity.PlatformPrincipal;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@RestController
@RequestMapping("/api/v1/admin/evaluations")
public class EvaluationController {
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final ChatAnalysisService analysis;
    public EvaluationController(JdbcTemplate jdbc,ObjectMapper json,ChatAnalysisService analysis){this.jdbc=jdbc;this.json=json;this.analysis=analysis;}
    @GetMapping("/cases") public List<Map<String,Object>> cases(){return jdbc.queryForList("SELECT id,name,question,source_type,expected_terms_json,enabled,created_at,updated_at FROM evaluation_case ORDER BY created_at DESC");}
    @PostMapping("/cases") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> create(@Valid @RequestBody CaseRequest body,Authentication authentication)throws Exception{UUID id=UUID.randomUUID();var now=com.agentplatform.common.DatabaseTime.now();jdbc.update("INSERT INTO evaluation_case(id,name,question,source_type,expected_terms_json,enabled,created_by,created_at,updated_at) VALUES(?,?,?,?,?,TRUE,?,?,?)",id.toString(),body.name.trim(),body.question.trim(),body.sourceType,json.writeValueAsString(body.expectedTerms.stream().map(String::trim).filter(x->!x.isBlank()).distinct().toList()),actor(authentication).id().toString(),now,now);return Map.of("id",id.toString());}
    @PatchMapping("/cases/{id}") public void enable(@PathVariable UUID id,@RequestBody EnabledRequest body){int changed=jdbc.update("UPDATE evaluation_case SET enabled=?,updated_at=? WHERE id=?",body.enabled,com.agentplatform.common.DatabaseTime.now(),id.toString());if(changed==0)throw new BusinessException(404,"EVALUATION_CASE_NOT_FOUND","评测用例不存在");}
    @DeleteMapping("/cases/{id}") public void delete(@PathVariable UUID id){Integer runs=jdbc.queryForObject("SELECT COUNT(*) FROM evaluation_run WHERE case_id=?",Integer.class,id.toString());if(runs!=null&&runs>0)throw new BusinessException(409,"EVALUATION_CASE_HAS_RUNS","已有运行记录的用例只能停用，不能删除");int changed=jdbc.update("DELETE FROM evaluation_case WHERE id=?",id.toString());if(changed==0)throw new BusinessException(404,"EVALUATION_CASE_NOT_FOUND","评测用例不存在");}
    @GetMapping("/runs") public List<Map<String,Object>> runs(){return jdbc.queryForList("SELECT r.id,r.case_id,c.name,r.task_id,r.status,r.score,r.matched_terms_json,r.created_at,r.completed_at FROM evaluation_run r JOIN evaluation_case c ON c.id=r.case_id ORDER BY r.created_at DESC LIMIT 200");}
    @GetMapping("/summary") public Map<String,Object> summary(){Map<String,Object> feedback=jdbc.queryForMap("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN feedback_rating='HELPFUL' THEN 1 ELSE 0 END),0) helpful,COALESCE(SUM(CASE WHEN feedback_rating='UNHELPFUL' THEN 1 ELSE 0 END),0) unhelpful FROM chat_message WHERE feedback_rating IS NOT NULL");Map<String,Object> runs=jdbc.queryForMap("SELECT COUNT(*) total,COALESCE(AVG(score),0) average_score FROM evaluation_run WHERE status='COMPLETED'");return Map.of("feedback",feedback,"evaluations",runs);}
    @PostMapping("/cases/{id}/runs") @Transactional @ResponseStatus(HttpStatus.ACCEPTED) public Map<String,Object> run(@PathVariable UUID id,@Valid @RequestBody RunRequest body,Authentication authentication){List<Map<String,Object>> items=jdbc.queryForList("SELECT question,source_type FROM evaluation_case WHERE id=? AND enabled=TRUE",id.toString());if(items.isEmpty())throw new BusinessException(404,"EVALUATION_CASE_NOT_FOUND","启用的评测用例不存在");List<Map<String,Object>> sources=jdbc.queryForList("SELECT type FROM data_source WHERE id=? AND enabled=TRUE",body.sourceId.toString());if(sources.isEmpty())throw new BusinessException(422,"CONFIG_NOT_AVAILABLE","数据源未启用");Map<String,Object> item=items.getFirst(),source=sources.getFirst();if(!Objects.equals(String.valueOf(item.get("source_type")),String.valueOf(source.get("type"))))throw new BusinessException(422,"EVALUATION_SOURCE_MISMATCH","评测用例与数据源类型不匹配");Integer model=jdbc.queryForObject("SELECT COUNT(*) FROM model_config WHERE id=? AND enabled=TRUE",Integer.class,body.modelId.toString());if(model==null||model==0)throw new BusinessException(422,"CONFIG_NOT_AVAILABLE","模型未启用");UUID conversation=UUID.randomUUID(),userMessage=UUID.randomUUID(),assistantMessage=UUID.randomUUID(),task=UUID.randomUUID(),run=UUID.randomUUID();var now=com.agentplatform.common.DatabaseTime.now();String userId=actor(authentication).id().toString();jdbc.update("INSERT INTO chat_conversation(id,user_id,title,model_id,source_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)",conversation.toString(),userId,"[评测] "+id,body.modelId.toString(),body.sourceId.toString(),now,now);jdbc.update("INSERT INTO chat_message(id,conversation_id,role,content,status,created_at) VALUES(?,?,'USER',?,'COMPLETED',?)",userMessage.toString(),conversation.toString(),String.valueOf(item.get("question")),now);jdbc.update("INSERT INTO chat_message(id,conversation_id,role,content,status,created_at) VALUES(?,?,'ASSISTANT','','RUNNING',?)",assistantMessage.toString(),conversation.toString(),now);jdbc.update("INSERT INTO analysis_task(id,conversation_id,user_message_id,assistant_message_id,status,stage,evaluation_case_id,created_at,updated_at) VALUES(?,?,?,?,'QUEUED','QUEUED',?,?,?)",task.toString(),conversation.toString(),userMessage.toString(),assistantMessage.toString(),id.toString(),now,now);jdbc.update("INSERT INTO evaluation_run(id,case_id,task_id,status,created_at) VALUES(?,?,?,'RUNNING',?)",run.toString(),id.toString(),task.toString(),now);analysis.run(task);return Map.of("runId",run.toString(),"taskId",task.toString());}
    private static PlatformPrincipal actor(Authentication authentication){return (PlatformPrincipal)authentication.getPrincipal();}
    public record CaseRequest(@NotBlank @Size(max=120) String name,@NotBlank @Size(max=4000) String question,@NotBlank @Pattern(regexp="MYSQL|ELASTICSEARCH") String sourceType,@NotEmpty @Size(max=20) List<@NotBlank @Size(max=100) String> expectedTerms){}
    public record EnabledRequest(boolean enabled){}
    public record RunRequest(@NotNull UUID modelId,@NotNull UUID sourceId){}
}
